# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 180050cfff59e947045c8a41ff26221ff0af354ee23c9e087783a19f5f11dd819fabc2916988685108d423cbc14fea7f4c24f31230d87803f263ba8dac00c099

test:
  secret_key_base: d51f3a6d0211e3dafb1d7c1772842e6834fb81ad35e2ff8b6a2db28da1067881e51bead938593a90294f1ee78bd0829f73f6a1568b645cdc6681c264a7696be1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
